options:
  logging: CLOUD_LOGGING_ONLY
steps:
  - name: 'gcr.io/cloud-builders/docker' # image prebuild oleh google
    args: ['build', '-t', 'gcr.io/innate-agency-463613-e6/fastapi-app:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/innate-agency-463613-e6/fastapi-app:latest']

images:
  - 'gcr.io/innate-agency-463613-e6/fastapi-app:latest'
